name: pomodoro_app
description: A Pomodoro mobile application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.17.3
  cupertino_icons: ^1.0.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/pomodoro.png"

flutter:

  uses-material-design: true

  assets:
    - lib/assets/sounds/484344__inspectorj__bike-bell-ding-single-01-01.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Medium.ttf
        - asset: lib/assets/fonts/Roboto-Light.ttf
    - family: Lobster
      fonts:
        - asset: lib/assets/fonts/Lobster-Regular.ttf

